In [1]:
#### HOMEWORK (voir cours portfolio)
##Photo 1 = equally dependant
##Markoviks photo 2et3 -- prime is transpose
##ERC Equally risk contribution

##2 by 2-- par email -- use son lien pour import la data -- proficient way of coding 
#ajouter des commentaires

#une strategy donne un pnl 
#you dont compute cov matrix a each date juste

In [2]:
import numpy as np
from datetime import datetime
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm
from strategy2 import Strategy

In [3]:
data = pd.read_excel('Excel.xlsx',sheet_name= 'Data')

,QDT FP Equity,PX_LAST,MARKETCAP,DIM FP Equity,PX_LAST.1,MARKETCAP.1,RUI FP Equity,PX_LAST.2,MARKETCAP.2,OR FP Equity,...,MARKETCAP.116,ATE FP Equity,PX_LAST.117,MARKETCAP.117,WLN FP Equity,PX_LAST.118,MARKETCAP.118,NXI FP Equity,PX_LAST.119,MARKETCAP.119
0,40543,65.20,2074.1424,40543,6.28,640.6889,40543,21.1225,1224.8148,40543,...,7045.2320,40543,24.585,785.1392,41816.0,16.4,NaN,40543,26.4957,1770.6669
1,40546,65.41,2080.8229,40546,6.29,641.5386,40546,21.3261,1236.6203,40546,...,7356.5732,40546,24.700,788.8118,41817.0,16.4,2160.9760,40546,26.8603,1795.0327
2,40547,66.54,2116.7705,40547,6.28,640.6889,40547,21.3770,1239.5716,40547,...,7370.2285,40547,25.090,801.2667,41820.0,16.6,2187.3294,40547,27.2288,1819.6576
3,40548,66.51,2115.8161,40548,6.29,641.3687,40548,21.6896,1257.7014,40548,...,7544.1062,40548,25.000,798.3925,41821.0,16.4,2160.9760,40548,27.1047,1811.3629
4,40549,67.56,2149.2187,40549,6.30,642.3883,40549,21.6920,1257.8420,40549,...,7652.4383,40549,25.450,812.7636,41822.0,16.3,2147.7993,40549,27.1861,1816.8063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2729,44440,23.72,819.8323,44440,524.20,48320.8556,44440,33.2700,3459.1215,44440,...,34554.1988,44440,138.700,4765.8506,NaN,NaN,NaN,44440,43.5800,2446.1334
2730,44441,23.76,821.2148,44441,532.60,49095.1692,44441,33.2000,3451.8435,44441,...,34567.8674,44441,139.900,4807.0836,NaN,NaN,NaN,44441,43.3600,2433.7848
2731,44442,23.28,804.6246,44442,531.00,48947.6809,44442,32.9700,3427.9301,44442,...,34535.9740,44442,139.800,4803.6475,NaN,NaN,NaN,44442,43.6600,2450.6237
2732,44445,22.80,788.0344,44445,542.40,49998.5351,44445,33.0000,3431.0493,44445,...,34804.7896,44445,138.700,4765.8506,NaN,NaN,NaN,44445,43.6200,2448.3786
2733,44446,22.78,787.3432,44446,543.20,50072.2803,44446,32.9500,3425.8508,44446,...,34827.5717,44446,139.900,4807.0834,NaN,NaN,NaN,44446,43.6800,2451.7464

Ici nous allons clean le dataframe puis trier l'excel pour extraire les market cap du 31 dec 2018

In [12]:
#liste de dataframe chaque df = date +mk

from curses.panel import top_panel


df_mkt_cap_list = []
for i in tqdm(range(120)):
    mkt_cap_data = data.iloc[:,[3*i,3*i+2]].copy()
    mkt_cap_data.dropna(inplace = True)
    mkt_cap_data.iloc[:,0] = pd.to_datetime(mkt_cap_data.iloc[:,0], unit= 'D', origin= '1899-12-30') #convesion des chiffres en date
    mkt_cap_data.rename(columns = {mkt_cap_data.columns[0] : 'Date', mkt_cap_data.columns[1]: mkt_cap_data.columns[0]}, inplace = True) #renomme les colonnes avec nom  +mkt
    mkt_cap_data.set_index('Date', inplace = True)
    df_mkt_cap_list.append(mkt_cap_data)


mkt_cap_data

#fusionne chaque dataframe par rapport a la date
agg_mkt_cap_data = df_mkt_cap_list[0]
for df in tqdm(df_mkt_cap_list[1:]):
   agg_mkt_cap_data = agg_mkt_cap_data.join(df, how='outer', sort = True)  

n=10
top = agg_mkt_cap_data[(agg_mkt_cap_data.index == '31-12-2018')].transpose().nlargest(n,columns = '2018-12-31').copy()

100%|██████████| 120/120 [00:00<00:00, 258.44it/s]
100%|██████████| 119/119 [00:00<00:00, 391.90it/s]
/usr/local/lib/python3.9/site-packages/pandas/core/arraylike.py:40: UserWarning: Parsing '31-12-2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  return self._cmp_method(other, operator.eq)

In [13]:
top.transpose()

,MC FP Equity,TTE FP Equity,OR FP Equity,SAN FP Equity,AIR FP Equity,KER FP Equity,RMS FP Equity,BNP FP Equity,EL FP Equity,AI FP Equity
Date,,,,,,,,,,
2018-12-31,130414.5455,124001.7374,112743.5012,94825.2974,65183.8473,51976.5689,51180.0509,49335.7982,47106.2711,46453.6329

In [17]:
price_df_list = []
for i in tqdm(range(120)):
    price_data = data.iloc[:,3*i:3*i+2].copy()
    price_data.dropna(inplace=True)
    price_data.iloc[:,0] = pd.to_datetime(price_data.iloc[:,0], unit= 'D', origin= '1899-12-30')
    price_data.rename(columns = {price_data.columns[0] : 'Date', price_data.columns[1]: price_data.columns[0]}, inplace = True)
    price_data.set_index('Date', inplace = True)
    price_df_list.append(price_data)


agg_price_data = price_df_list[0]
for df in tqdm(price_df_list[1:]):
    agg_price_data = agg_price_data.join(df, how='outer', sort = True)

#agg_price_data = agg_price_data[(agg_price_data.index >= '31/12/2018') & (agg_price_data.index <= '31/12/2020')].copy()

100%|██████████| 120/120 [00:00<00:00, 284.33it/s]
100%|██████████| 119/119 [00:00<00:00, 684.49it/s]

In [18]:
agg_price_data = agg_price_data[(agg_price_data.index >= '2018-12-31') & (agg_price_data.index <= '2019-12-31')].copy() #Sélectionne l'année 2019

top10 = pd.concat([top.T, agg_price_data], join = 'inner') #Sélectionne les résultats de 2019 des 10 meilleurs market cap de 2018
top10 = top10.drop(top10.index[[1]]) #commence de le 02 janv 2019 car férié le 1er.

,MC FP Equity,TTE FP Equity,OR FP Equity,SAN FP Equity,AIR FP Equity,KER FP Equity,RMS FP Equity,BNP FP Equity,EL FP Equity,AI FP Equity
Date,,,,,,,,,,
2019-01-02,253.30,46.655,199.60,75.40,84.17,402.8,477.6,39.085,110.70,96.4545
2019-01-03,243.65,46.255,197.20,74.66,81.21,380.7,464.0,38.855,109.65,94.6818
2019-01-04,251.15,47.410,200.00,75.34,85.12,397.4,477.8,40.740,110.80,97.3182
2019-01-07,250.70,47.300,197.45,73.84,83.56,396.4,472.2,40.680,110.60,96.7727
2019-01-08,258.55,47.200,198.65,74.42,86.65,410.5,479.9,40.885,111.20,96.9091
...,...,...,...,...,...,...,...,...,...,...
2019-12-23,413.80,49.355,265.30,90.71,132.78,582.0,676.6,53.110,138.15,126.4500
2019-12-24,414.10,49.475,264.50,90.63,133.14,587.4,678.0,52.980,138.60,126.0000
2019-12-27,417.60,49.290,266.10,90.84,133.28,590.7,677.4,52.970,139.15,126.8500
2019-12-30,414.60,49.185,263.20,89.75,130.00,586.3,671.2,52.730,134.90,125.9500
2019-12-31,414.20,49.200,264.00,89.62,130.48,585.2,666.2,52.830,135.80,126.2000

On trie le agg_mkt par ordre croissant + enlever les valeurs nulles